---
title: "Final Project"
author: "Eric Holberg"
date: "6/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install and load libraries
```{r Librarys}

library("ggplot2", "pdflatex")
library("dplyr") #was getting an error when it was in the line above?
library("tidyr")
library("usmap")
```


```{r Data Pre-processing for Final Project}

deaths <-read.csv("us_county_deaths1.csv")

mask <- read.csv("mask_use.csv")

summary(deaths)#showing a 5 point summary for the data
summary(mask)
head(deaths)#shows the first 6 lines of data
head(mask)

```
```{r Transform mask data}

mask.tidy <- gather(mask, key = "Category", value = "Response", 2:6, factor_key = T)
head(mask.tidy)


```

```{r plots test}

scatterCD <- ggplot(deaths, aes(state,deaths)) +
  geom_point()

#scatterCD



mask.hist <- ggplot(mask.tidy, aes(Response, color = Category, fill = Category))+
  geom_histogram(bins = 50, alpha=0.5, position="identity")

  

mask.hist
# mask.hist.rarely
# mask.hist.SOMETIMES
# mask.hist.FREQUENTLY
# mask.hist.ALWAYS


```

```{r US MAP TESTING}

plot_usmap(
  data = mask.tidy, values = mask.tidy$ï..COUNTYFP)
                  


```
